# fly.toml app configuration file generated for finance-telebot-1 on 2024-01-21T18:44:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "finance-telebot-1"
primary_region = "otp"

[build]
dockerfile='./Dockerfile'

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
